name: HackersGoHome
author: L3OShow
version: 2.9
description: Prevent hackers from grief your server with passwords and restrictions!
main: me.l3oshow.hgh.HGH

commands:
    logme: 
        usage: /logme <password>
        description: Log yourself
    antigrief:
        usage: /antigrief <password>
        description: Log yourself to access dangerous commands