name: HackersGoHome
author: L3OShow
version: 2.6
description: Prevent hackers from grief your server with passwords and restrictions!
main: me.l3oshow.hgh.HGH

commands:
    logme: 
        usage: /logme <password>
        description: Permette di loggarti
    antigrief:
        usage: /antigrief <password>
        description: Ti da accesso ai comandi pericolosi